export const USER_FETCH_REQUESTED = '@task/USER_FETCH_REQUESTED'
export const USER_FETCH_FAILED = '@task/USER_FETCH_FAILED'
export const ADD_TASK = '@task/ADD_TASK'
export const REMOVE_TASK_BY_ID = '@task/REMOVE_TASK_BY_ID'
export const COMPLETE_TASK_BY_ID = '@task/COMPLETE_TASK_BY_ID'
export const DO_LATER_TASK_BY_ID = '@task/DO_LATER_TASK_BY_ID'
